Remove unused `min` function
This was failing to compile with:

    testlock.c:112:19: error: unused function 'min' [-Werror,-Wunused-function]
    static inline int min(int a, int b) { return a < b ? a : b; }
                      ^
    1 error generated.